apiVersion: v1
kind: Service
metadata:
  name: kubeagent
  namespace: kubeagent
spec:
  selector:
    app: kubeagent
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: health
      port: 8001
      targetPort: health
